#!/bin/sh
#
# This script gathers information about all of the network devices
# visible within the current network namespace.

[ $# -eq 1 ] || exit 1

ns=$1

ls /sys/class/net |
while read dev; do
	[ "$dev" = lo ] && continue
	[ "$dev" = ovs-system ] && continue
	
	devpath=/sys/class/net/$dev
	driver=$( ethtool -i $dev | awk '/driver:/ {print $2}' 2> /dev/null)

	if [ "$driver" = veth ]; then
		ifindex=$(cat $devpath/ifindex)
		peer_ifindex=$(ethtool -S $dev | awk '/peer_ifindex/ {print $2}')
		echo "$dev $ifindex $peer_ifindex" >> peers
	elif [ "$driver" = openvswitch ] && ovs-vsctl br-exists $dev; then
		driver=ovsbridge
		ovs-vsctl list-ports $dev |
		while read port; do
			echo "$port $dev" >> edges
		done
	elif [ "$driver" = openvswitch ]; then
		driver=ovsport
	elif [ "$driver" = bridge ]; then
		ls $devpath/brif |
		while read port; do
			echo "$dev $port" >> edges
		done
	fi

	echo "$dev $driver $ns" >> nodes
done

